// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljfrgcmmoioihzkjylhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZnJnY21tb2lvaWh6a2p5bGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzQ3MjEsImV4cCI6MjA2ODE1MDcyMX0.dDqY6jKsdMba1F378z6Xm3j8pkftcimCOaAeI-Y51fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});