// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixunnbbfeyzdtnjaokpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4dW5uYmJmZXl6ZHRuamFva3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDI1MTksImV4cCI6MjA2NzYxODUxOX0.nxWnOdA9CsopSX-XVnGiP7l48tQsTzqKZzsopWgu7fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});